import fs from "fs";
const path = "src/pages/VerificationSuccess.vue";
let text = fs.readFileSync(path, "utf8");
const target = `          <section v-if="statusKey === 'unused'" class="space-y-5">\r\n            <Alert variant="default">\r\n              <AlertTitle>卡密未使??/AlertTitle>\r\n              <AlertDescription>\r\n                填写收件邮箱后，系统将自动发送邀请邮件??              </AlertDescription>\r\n            </Alert>`;
if (!text.includes(target)) {
  throw new Error('target block not found');
}
const replacement = `          <section v-if="statusKey === 'unused'" class="space-y-5">\r\n            <Alert variant="default">\r\n              <AlertTitle>卡密未使用</AlertTitle>\r\n              <AlertDescription class="space-y-2">\r\n                <p class="text-sm leading-relaxed text-slate-600">\r\n                  绑定邮箱前，请先确认 GPT 注册邮箱，确保填写的信息准确无误。\r\n                </p>\r\n                <details class="group space-y-1 text-xs leading-relaxed text-slate-600">\r\n                  <summary\r\n                    class="cursor-pointer text-sm font-medium text-primary transition hover:underline group-open:text-primary/80"\r\n                  >\r\n                    如何确认 GPT 注册邮箱？\r\n                  </summary>\r\n                  <ol class="list-decimal space-y-1 pl-4">\r\n                    <li>\r\n                      登录\r\n                      <a\r\n                        href="https://chatgpt.com"\r\n                        target="_blank"\r\n                        rel="noopener noreferrer"\r\n                        class="text-primary hover:underline"\r\n                      >\r\n                        chatgpt.com\r\n                      </a>\r\n                      并保持会话。\r\n                    </li>\r\n                    <li>\r\n                      在同一浏览器打开\r\n                      <a\r\n                        href="https://chatgpt.com/api/auth/session"\r\n                        target="_blank"\r\n                        rel="noopener noreferrer"\r\n                        class="text-primary hover:underline"\r\n                      >\r\n                        /api/auth/session\r\n                      </a>\r\n                      页面。\r\n                    </li>\r\n                    <li>\r\n                      页面返回的 JSON 数据中\r\n                      <span class="font-mono text-slate-700">user.email</span>\r\n                      字段即为当前绑定的邮箱。\r\n                    </li>\r\n                  </ol>\r\n                </details>\r\n              </AlertDescription>\r\n            </Alert>`;
text = text.replace(target, replacement);
fs.writeFileSync(path, text, "utf8");
